name: 'App Center + Release Notes'
description: 'GitHub Action that uploads artefacts for Visual Studio App Center'
author: 'Zach Silveira <@zackify>'
inputs: 
  appName:
    description: 'App name followed by username e.g. wzieba/Sample-App'
    required: true 
  token:
    description: 'Upload token - you can get one from appcenter.ms/settings'
    required: true 
  group:
    description: 'Distribution group'
    required: true
  file:
    description: 'Artefact to upload (.apk or .ipa)'
    required: true
branding:
  color: 'red' 
  icon: 'send'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.appName }}
    - ${{ inputs.token }}
    - ${{ inputs.group }}
    - ${{ inputs.file }}
    - ${{ inputs.releaseNotes }}
